// EREM Group - Pompa ve Hidrofor Secimi

// Bu dosya, ERM Pompa Secim Teklif Sistemi V1 Excel dosyasindaki 3_Urun_DB,
// 6_Alarko_Optima_DB ve 9_Listeler sayfalarindan otomatik uretilmistir.
// ONEMLI: 3_Urun_DB'deki urunler Excel'de ORNEK VERI olarak isaretlenmistir.
// Gercek marka/model/fiyat listesi ile degistirilmeden musteriye teklif verilmemelidir.

window.PUMP_PRODUCTS = [
  {
    "brand": "Masdaf",
    "model": "MSD-H 2/16",
    "category": "Hidrofor",
    "pumpType": "Dik milli çok kademeli",
    "qMin": 2,
    "qMax": 5,
    "hMin": 45,
    "hMax": 70,
    "bepQ": 3.5,
    "bepH": 58,
    "motorKW": 1.5,
    "pumpCount": 2,
    "frequency": "Var",
    "electric": "Trifaze",
    "dn": "DN32",
    "bodyMat": "Döküm",
    "fanMat": "Noryl",
    "maxTemp": 40,
    "maxPressure": 10,
    "usage": "Konut basınçlandırma",
    "stockCode": null,
    "listPrice": 100000,
    "currency": "TRY",
    "discountPct": 0.3,
    "netPrice": 70000,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "Wilo",
    "model": "WLO-H 3/14",
    "category": "Hidrofor",
    "pumpType": "Dik milli çok kademeli",
    "qMin": 3,
    "qMax": 6,
    "hMin": 50,
    "hMax": 75,
    "bepQ": 4.5,
    "bepH": 62,
    "motorKW": 1.5,
    "pumpCount": 2,
    "frequency": "Var",
    "electric": "Trifaze",
    "dn": "DN32",
    "bodyMat": "Paslanmaz",
    "fanMat": "Paslanmaz",
    "maxTemp": 50,
    "maxPressure": 16,
    "usage": "Konut basınçlandırma",
    "stockCode": null,
    "listPrice": 120000,
    "currency": "TRY",
    "discountPct": 0.25,
    "netPrice": 90000,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "Grundfos",
    "model": "GRF-H 2/18",
    "category": "Hidrofor",
    "pumpType": "Dik milli çok kademeli",
    "qMin": 2,
    "qMax": 5,
    "hMin": 50,
    "hMax": 80,
    "bepQ": 3.5,
    "bepH": 65,
    "motorKW": 1.5,
    "pumpCount": 2,
    "frequency": "Var",
    "electric": "Trifaze",
    "dn": "DN32",
    "bodyMat": "Paslanmaz",
    "fanMat": "Paslanmaz",
    "maxTemp": 60,
    "maxPressure": 16,
    "usage": "Konut basınçlandırma",
    "stockCode": null,
    "listPrice": 140000,
    "currency": "TRY",
    "discountPct": 0.2,
    "netPrice": 112000,
    "stock": "Yok",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "Wilo",
    "model": "WLO-S 25/6",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu",
    "qMin": 0.5,
    "qMax": 4,
    "hMin": 2,
    "hMax": 6,
    "bepQ": 2,
    "bepH": 4,
    "motorKW": 0.05,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN25",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 95,
    "maxPressure": 10,
    "usage": "Radyatör devresi",
    "stockCode": null,
    "listPrice": 9000,
    "currency": "TRY",
    "discountPct": 0.3,
    "netPrice": 6300,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "Grundfos",
    "model": "GRF-S 25/8",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu",
    "qMin": 0.8,
    "qMax": 5,
    "hMin": 3,
    "hMax": 8,
    "bepQ": 2.5,
    "bepH": 5.5,
    "motorKW": 0.09,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN25",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 95,
    "maxPressure": 10,
    "usage": "Radyatör devresi",
    "stockCode": null,
    "listPrice": 11000,
    "currency": "TRY",
    "discountPct": 0.25,
    "netPrice": 8250,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "DAB",
    "model": "DAB-S 32/8",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu",
    "qMin": 1,
    "qMax": 6,
    "hMin": 3,
    "hMax": 8,
    "bepQ": 3,
    "bepH": 5.5,
    "motorKW": 0.09,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN32",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 95,
    "maxPressure": 10,
    "usage": "Radyatör / fan coil",
    "stockCode": null,
    "listPrice": 8500,
    "currency": "TRY",
    "discountPct": 0.35,
    "netPrice": 5525,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "Standart Pompa",
    "model": "STD-K 50/160",
    "category": "Kazan dairesi pompası",
    "pumpType": "Inline kuru rotorlu",
    "qMin": 10,
    "qMax": 40,
    "hMin": 8,
    "hMax": 18,
    "bepQ": 25,
    "bepH": 13,
    "motorKW": 3,
    "pumpCount": 1,
    "frequency": "Yok",
    "electric": "Trifaze",
    "dn": "DN50",
    "bodyMat": "Döküm",
    "fanMat": "Döküm",
    "maxTemp": 110,
    "maxPressure": 16,
    "usage": "Kazan primer devre",
    "stockCode": null,
    "listPrice": 65000,
    "currency": "TRY",
    "discountPct": 0.3,
    "netPrice": 45500,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "Masdaf",
    "model": "MSD-K 65/160",
    "category": "Kazan dairesi pompası",
    "pumpType": "Inline kuru rotorlu",
    "qMin": 15,
    "qMax": 55,
    "hMin": 8,
    "hMax": 20,
    "bepQ": 35,
    "bepH": 14,
    "motorKW": 4,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Trifaze",
    "dn": "DN65",
    "bodyMat": "Döküm",
    "fanMat": "Döküm",
    "maxTemp": 120,
    "maxPressure": 16,
    "usage": "Kazan primer devre",
    "stockCode": null,
    "listPrice": 78000,
    "currency": "TRY",
    "discountPct": 0.28,
    "netPrice": 56160,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "KSB",
    "model": "KSB-K 50/160",
    "category": "Kazan dairesi pompası",
    "pumpType": "Inline kuru rotorlu",
    "qMin": 10,
    "qMax": 45,
    "hMin": 10,
    "hMax": 20,
    "bepQ": 27,
    "bepH": 15,
    "motorKW": 4,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Trifaze",
    "dn": "DN50",
    "bodyMat": "Döküm",
    "fanMat": "Bronz",
    "maxTemp": 120,
    "maxPressure": 16,
    "usage": "Kazan / kolektör",
    "stockCode": null,
    "listPrice": 95000,
    "currency": "TRY",
    "discountPct": 0.22,
    "netPrice": 74100,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "Wilo",
    "model": "WLO-V 65/12",
    "category": "HVAC pompası",
    "pumpType": "Inline frekanslı",
    "qMin": 20,
    "qMax": 80,
    "hMin": 6,
    "hMax": 14,
    "bepQ": 50,
    "bepH": 10,
    "motorKW": 5.5,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Trifaze",
    "dn": "DN65",
    "bodyMat": "Döküm",
    "fanMat": "Döküm",
    "maxTemp": 120,
    "maxPressure": 16,
    "usage": "Chiller devresi",
    "stockCode": null,
    "listPrice": 145000,
    "currency": "TRY",
    "discountPct": 0.25,
    "netPrice": 108750,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "EBARA",
    "model": "EBR-D 65",
    "category": "Drenaj pompası",
    "pumpType": "Dalgıç",
    "qMin": 5,
    "qMax": 25,
    "hMin": 5,
    "hMax": 15,
    "bepQ": 15,
    "bepH": 10,
    "motorKW": 1.5,
    "pumpCount": 1,
    "frequency": "Yok",
    "electric": "Trifaze",
    "dn": "DN65",
    "bodyMat": "Döküm",
    "fanMat": "Döküm",
    "maxTemp": 40,
    "maxPressure": 6,
    "usage": "Drenaj çukuru",
    "stockCode": null,
    "listPrice": 42000,
    "currency": "TRY",
    "discountPct": 0.3,
    "netPrice": 29400,
    "stock": "Var",
    "docLink": null,
    "note": "ÖRNEK VERİ – gerçek liste ile değiştirin"
  },
  {
    "brand": "DAB",
    "model": "DAB-P 80 Öğütücülü",
    "category": "Pis su pompası",
    "pumpType": "Dalgıç öğütücülü",
    "qMin": 3,
    "qMax": 18,
    "hMin": 6,
    "hMax": 18,
    "bepQ": 10,
    "bepH": 12,
    "motorKW": 2.2,
    "pumpCount": 1,
    "frequency": "Yok",
    "electric": "Trifaze",
    "dn": "DN80",
    "bodyMat": "Döküm",
    "fanMat": "Döküm",
    "maxTemp": 40,
    "maxPressure": 6,
    "usage": "Pis su terfi",
    "stockCode": null,
    "listPrice": 56000,
    "currency": "TRY",
    "discountPct": 0.3,
    "netPrice": 39200,
    "stock": "Var",
    "docLink": null,
    "note": "Alarko Optima değişken + sabit basınç grafikleri baz alınmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 4/4",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 11.3,
    "hMin": 0.5,
    "hMax": 5.4,
    "bepQ": 6.1,
    "bepH": 3.2,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 4/12",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 30.2,
    "hMin": 0.2,
    "hMax": 12.6,
    "bepQ": 11.3,
    "bepH": 7.8,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 4/18",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 57.6,
    "hMin": 0.2,
    "hMax": 17.5,
    "bepQ": 14.9,
    "bepH": 11.1,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 5/8",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 15.9,
    "hMin": 0.4,
    "hMax": 8,
    "bepQ": 8.2,
    "bepH": 5.2,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 5/9",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 25.5,
    "hMin": 0.4,
    "hMax": 9.2,
    "bepQ": 11.6,
    "bepH": 5.9,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 5/12",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 29.9,
    "hMin": 0.2,
    "hMax": 12.6,
    "bepQ": 14.3,
    "bepH": 7.8,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 5/18",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 57.7,
    "hMin": 0.2,
    "hMax": 17.8,
    "bepQ": 23.1,
    "bepH": 11.1,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 6/9",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 30.2,
    "hMin": 0.2,
    "hMax": 10.4,
    "bepQ": 14.3,
    "bepH": 5.9,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 6/12",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 44.7,
    "hMin": 0.2,
    "hMax": 12.6,
    "bepQ": 22.6,
    "bepH": 6.5,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları Alarko Optima katalog PDF'inin 'Genel Seçim Abağı' grafiğindeki vektör verisinden sayısallaştırılmıştır"
  },
  {
    "brand": "Alarko",
    "model": "OPTIMA 8/12",
    "category": "Sirkülasyon pompası",
    "pumpType": "Islak rotorlu frekanslı",
    "qMin": 0,
    "qMax": 57.5,
    "hMin": 0.2,
    "hMax": 12.7,
    "bepQ": 31.6,
    "bepH": 8.4,
    "motorKW": null,
    "pumpCount": 1,
    "frequency": "Var",
    "electric": "Monofaze",
    "dn": "DN bilgisi katalogdan kontrol",
    "bodyMat": "Döküm",
    "fanMat": "Kompozit",
    "maxTemp": 110,
    "maxPressure": 10,
    "usage": "Isıtma devresi / HVAC sirkülasyon",
    "stockCode": null,
    "listPrice": 0,
    "currency": "TRY",
    "discountPct": 0,
    "netPrice": 0,
    "stock": "Kontrol",
    "docLink": "ALARKO sirkulasyon-pompasi-alarko-optima-brs-tr (7).pdf",
    "note": "Q/H sınırları, Alarko Optima katalog PDF'inin (sirkulasyon-pompasi-alarko-optima-brs-tr.pdf) 'Genel Seçim Abağı' grafiğindeki vektör verisinden birebir sayısallaştırılmıştır; önceden veri setinde eksikti."
  }
];

// NOT: Asagidaki degisken basinc alanlari (qMaxVar/altH0/.../ustHson) artik
// Degisken Basinc (Vp) modeli belirlemek icin KULLANILMIYOR - onun yerine
// asagidaki window.ALARKO_REGIONS'taki PDF'ten birebir sayisallastirilmis
// poligon verisi kullaniliyor (bkz. script.js calcAlarko). Bu alanlar sadece
// Sabit Basinc (Cp) hesabi icin (sabitHalt/sabitQYataySon/sabitHust/...) hala
// gecerli ve kullaniliyor.
window.ALARKO_CURVES = [
  {
    "model": "OPTIMA 4/4",
    "pdfPage": 9,
    "qMaxVar": 11,
    "hMaxLabel": 5,
    "altH0": 1,
    "altHend": 2,
    "qTepe": 5,
    "ustH0": 2.5,
    "ustHtepe": 5,
    "qSon": 11,
    "ustHson": 2,
    "note": "PDF p.9 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 5,
    "sabitHust": 5,
    "sabitQSon": 11,
    "sabitHson": 1,
    "sabitNote": "PDF p.9 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 4/12",
    "pdfPage": 11,
    "qMaxVar": 20.5,
    "hMaxLabel": 12,
    "altH0": 2,
    "altHend": 4,
    "qTepe": 5,
    "ustH0": 6,
    "ustHtepe": 12,
    "qSon": 20.5,
    "ustHson": 4,
    "note": "PDF p.11 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 5,
    "sabitHust": 12,
    "sabitQSon": 20.5,
    "sabitHson": 1,
    "sabitNote": "PDF p.11 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 4/18",
    "pdfPage": 13,
    "qMaxVar": 27,
    "hMaxLabel": 17,
    "altH0": 2,
    "altHend": 4,
    "qTepe": 5,
    "ustH0": 7,
    "ustHtepe": 17,
    "qSon": 27,
    "ustHson": 4,
    "note": "PDF p.13 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 5,
    "sabitHust": 17,
    "sabitQSon": 27,
    "sabitHson": 1,
    "sabitNote": "PDF p.13 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 5/8",
    "pdfPage": 15,
    "qMaxVar": 15,
    "hMaxLabel": 8,
    "altH0": 1.5,
    "altHend": 3,
    "qTepe": 5,
    "ustH0": 3.8,
    "ustHtepe": 8,
    "qSon": 15,
    "ustHson": 3,
    "note": "PDF p.15 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 5,
    "sabitHust": 8,
    "sabitQSon": 15,
    "sabitHson": 1,
    "sabitNote": "PDF p.15 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 5/9",
    "pdfPage": 17,
    "qMaxVar": 21,
    "hMaxLabel": 9,
    "altH0": 2,
    "altHend": 4,
    "qTepe": 6,
    "ustH0": 4.5,
    "ustHtepe": 9,
    "qSon": 21,
    "ustHson": 4,
    "note": "PDF p.17 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 6,
    "sabitHust": 9,
    "sabitQSon": 21,
    "sabitHson": 1,
    "sabitNote": "PDF p.17 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 5/12",
    "pdfPage": 19,
    "qMaxVar": 26,
    "hMaxLabel": 12,
    "altH0": 2,
    "altHend": 4,
    "qTepe": 8,
    "ustH0": 6,
    "ustHtepe": 12,
    "qSon": 26,
    "ustHson": 4,
    "note": "PDF p.19 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 8,
    "sabitHust": 12,
    "sabitQSon": 26,
    "sabitHson": 1,
    "sabitNote": "PDF p.19 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 5/18",
    "pdfPage": 21,
    "qMaxVar": 42,
    "hMaxLabel": 17,
    "altH0": 2,
    "altHend": 4,
    "qTepe": 9,
    "ustH0": 8,
    "ustHtepe": 17,
    "qSon": 42,
    "ustHson": 4,
    "note": "PDF p.21 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 9,
    "sabitHust": 17,
    "sabitQSon": 42,
    "sabitHson": 1,
    "sabitNote": "PDF p.21 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 6/9",
    "pdfPage": 23,
    "qMaxVar": 26,
    "hMaxLabel": 9,
    "altH0": 2,
    "altHend": 4,
    "qTepe": 14,
    "ustH0": 4.5,
    "ustHtepe": 9,
    "qSon": 26,
    "ustHson": 4,
    "note": "PDF p.23 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 14,
    "sabitHust": 9,
    "sabitQSon": 26,
    "sabitHson": 1,
    "sabitNote": "PDF p.23 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 6/12",
    "pdfPage": 25,
    "qMaxVar": 41,
    "hMaxLabel": 10,
    "altH0": 2,
    "altHend": 4,
    "qTepe": 15,
    "ustH0": 5,
    "ustHtepe": 10,
    "qSon": 41,
    "ustHson": 4,
    "note": "PDF p.25 değişken basınç grafiğinden yaklaşık",
    "sabitHalt": 1,
    "sabitQYataySon": 15,
    "sabitHust": 10,
    "sabitQSon": 41,
    "sabitHson": 1,
    "sabitNote": "PDF p.25 sabit basınç grafiğinden yaklaşık"
  },
  {
    "model": "OPTIMA 8/12",
    "pdfPage": null,
    "qMaxVar": 57.5,
    "hMaxLabel": 13,
    "altH0": 2,
    "altHend": 4,
    "qTepe": 22,
    "ustH0": 6.5,
    "ustHtepe": 13,
    "qSon": 57.5,
    "ustHson": 4,
    "note": "Kullanıcı tarafından sağlanan referans birleşik pompa eğrisi grafiğinden yaklaşık okunmuştur",
    "sabitHalt": 1,
    "sabitQYataySon": 22,
    "sabitHust": 13,
    "sabitQSon": 57.5,
    "sabitHson": 1,
    "sabitNote": "Kullanıcı tarafından sağlanan referans grafikten yaklaşık"
  }
];

window.ALARKO_REGIONS = [
  // Alarko Optima "Genel Secim Abagi" (Degisken Basinc) grafiginden
  // PDF vektor verisi ile birebir sayisallastirilmistir (yaklasik degil).
  // Sira onemli: chart'ta kucuk pompalar buyuklerin ustune "boyanir";
  // bir Q/H noktasi birden fazla bolgeye denk geldiginde dizideki SON
  // (en sondaki = grafikte en ustte gorunen) esleseni gecerli kabul edilir.
  { "model": "OPTIMA 5/18", "points": [[0,17.75], [22.97,11.98], [23.96,11.8], [40.66,8.42], [57.69,4.09], [44.41,2.9], [44.79,2.74], [29.58,1.53], [30.31,1.05], [10.87,0.21], [9.64,0.51], [7.79,0.41], [6.69,0.74], [4.71,0.43], [1.68,0.85], [0,0.86]] },
  { "model": "OPTIMA 4/18", "points": [[0,17.54], [12.74,12.63], [24.84,11.67], [57.6,4.12], [56.25,3.95], [44.39,2.91], [44.86,2.71], [29.58,1.52], [30.05,1.25], [29.73,1], [11.3,0.22], [9.66,0.5], [8.12,0.43], [6.76,0.73], [4.76,0.45], [0,0.86]] },
  { "model": "OPTIMA 8/12", "points": [[0,12.57], [5.05,12.69], [25.06,11.64], [49.96,6.18], [57.45,4.12], [44.26,2.95], [44.73,2.8], [44.47,2.65], [29.56,1.52], [30.2,1.14], [29.75,1], [11.34,0.23], [10.4,0.3], [9.21,0.48], [7.64,0.42], [6.65,0.72], [4.69,0.44], [0.99,0.85], [0,0.86]] },
  { "model": "OPTIMA 6/12", "points": [[0,12.55], [5.9,11.79], [14.16,10.03], [30.33,7.09], [44.69,2.8], [44.13,2.63], [29.51,1.53], [29.77,0.99], [11.26,0.24], [9.58,0.53], [8.14,0.43], [6.72,0.74], [5.06,0.49], [4.24,0.58], [0,0.86]] },
  { "model": "OPTIMA 5/12", "points": [[0,12.57], [6.16,11.78], [11.73,10.84], [29.42,1.77], [29.9,1.31], [29.43,0.99], [11.39,0.21], [9.67,0.5], [7.9,0.39], [6.74,0.74], [4.69,0.46], [0,0.85]] },
  { "model": "OPTIMA 4/12", "points": [[0,12.57], [12.7,9.09], [13.81,8.77], [26.27,3.56], [30.18,1.15], [29.66,0.98], [11.23,0.21], [10.34,0.31], [9.61,0.54], [7.53,0.47], [6.5,0.75], [5.07,0.51], [4.14,0.59], [0,0.86]] },
  { "model": "OPTIMA 6/9", "points": [[0,10.37], [16.69,7.88], [30.2,1.15], [29.61,0.99], [11.41,0.23], [10.42,0.28], [9.71,0.56], [7.67,0.47], [6.44,0.76], [4.89,0.59], [0,1.16]] },
  { "model": "OPTIMA 5/9", "points": [[6.49,0.81], [7.92,0.41], [25.28,1.49], [25.48,1.66], [0,9.21], [0,0.9], [4.89,0.5]] },
  { "model": "OPTIMA 5/8", "points": [[0,0.84], [4.71,0.42], [15.95,2.32], [4.66,7.96], [0,8.02]] },
  { "model": "OPTIMA 4/4", "points": [[0,1.17], [4.99,0.5], [11.26,1.48], [4.66,5.05], [0,5.42]] }
];

window.PUMP_LISTS = {
  "Kategoriler": [
    "Hidrofor",
    "Sirkülasyon pompası",
    "Kazan dairesi pompası",
    "HVAC pompası",
    "Drenaj pompası",
    "Pis su pompası",
    "Yangın pompası",
    "Temiz su pompası",
    "Endüstriyel pompa",
    "Diğer"
  ],
  "EvetHayir": [
    "Evet",
    "Hayır"
  ],
  "EvetHayirFark": [
    "Evet",
    "Hayır",
    "Farketmez"
  ],
  "VarYok": [
    "Var",
    "Yok"
  ],
  "Elektrik": [
    "Monofaze",
    "Trifaze",
    "Farketmez"
  ],
  "Markalar": [
    "Farketmez",
    "Wilo",
    "Grundfos",
    "Masdaf",
    "Standart Pompa",
    "DAB",
    "EBARA",
    "KSB",
    "Diğer"
  ],
  "Aciliyet": [
    "Acil (aynı gün)",
    "Normal (1-2 gün)",
    "Planlı proje"
  ],
  "BinaTipi": [
    "Konut",
    "Villa",
    "Otel",
    "Okul",
    "İş merkezi",
    "Fabrika",
    "Diğer"
  ],
  "DepoKonum": [
    "Bodrum",
    "Zemin",
    "Çatı"
  ],
  "Emis": [
    "Pozitif",
    "Negatif"
  ],
  "SistemTipi": [
    "Tekli",
    "İkili",
    "Üçlü"
  ],
  "ParaBirimi": [
    "TRY",
    "EUR",
    "USD"
  ],
  "IsitmaSistemi": [
    "Radyatör",
    "Yerden ısıtma",
    "Fan coil",
    "Kazan devresi"
  ],
  "TalepTipi": [
    "Sadece fiyat",
    "Seçim + fiyat"
  ]
};
